# Generated by Django 4.2 on 2023-04-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Danbi", "단비"),
                            ("Darae", "다래"),
                            ("Blabla", "블라블라"),
                            ("Cheollo", "철로"),
                            ("DangE", "땅이"),
                            ("Haetae", "해태"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
