# Generated by Django 4.2 on 2023-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0004_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                choices=[
                    ("단비", "단비"),
                    ("다래", "다래"),
                    ("블라블라", "블라블라"),
                    ("철로", "철로"),
                    ("땅이", "땅이"),
                    ("해태", "해테"),
                    ("수피", "수피"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
