# Generated by Django 4.2 on 2023-04-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0004_alter_team_name"),
        ("Task", "0002_alter_subtask_completed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Team.team",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="Team.team",
            ),
        ),
    ]
