# Generated by Django 4.2 on 2023-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0003_alter_subtask_team_alter_task_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="completed_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
