# Generated by Django 4.2 on 2023-04-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("단비", "Danbi"),
                    ("다래", "Darae"),
                    ("블라블라", "Blabla"),
                    ("철로", "Cheollo"),
                    ("땅이", "DangE"),
                    ("해태", "Haetae"),
                ],
                default="Danbi",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
