# Generated by Django 4.2 on 2023-04-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_user_team_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="team",
        ),
    ]
